using System.Collections.Generic;
using System.Text;
using ContentKit;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace ElevatorRL
{
    /// <summary>
    /// Self-contained heuristic sandbox: drives the elevator simulation and builds the
    /// "Elevator RL Control Sandbox" uGUI dashboard. Mirrors the HTML renderVals() logic.
    /// Add this component to a child of the Canvas. The component builds the entire UI
    /// hierarchy under uiRoot on Start.
    /// </summary>
    public class ElevatorSandbox : MonoBehaviour
    {
        // ── Inspector ──────────────────────────────────────────────────────────

        [Header("ContentKit")]
        public CKTheme theme;

        [Header("Config assets (leave null for defaults)")]
        public BuildingConfig    buildingConfigAsset;
        public RewardConfig      rewardConfigAsset;
        public ObservationConfig observationConfigAsset;
        public TrafficConfig     trafficConfigAsset;

        [Header("Fonts (from TMP font assets, generated by editor setup)")]
        public TMP_FontAsset monoFont;
        public TMP_FontAsset displayFont;

        [Header("Start config")]
        public int   startFloors   = 8;
        public int   startCars     = 3;
        public int   startCapacity = 8;
        public int   speed         = 5;
        [Range(0f, 3f)] public float intensity = 1.0f;
        public TrafficPattern startPattern = TrafficPattern.UpPeak;
        public int   seed          = 1;
        public bool  showObservation = true;

        [Header("UI root (assign the Canvas RectTransform, or leave null to use parent)")]
        public RectTransform uiRoot;

        // ── Sim state ─────────────────────────────────────────────────────────

        Building      _b;
        BuildingConfig   _cfg;
        RewardConfig     _reward;
        ObservationConfig _obs;
        TrafficConfig    _traffic;

        bool   _playing;
        bool   _dayCycle;
        TrafficPattern _selectedPattern;
        int    _decisions;
        int    _utilSteps;
        double _total;
        float  _last;
        float  _decisionClock;
        float[] _utilSum;

        // ── Layout constants ───────────────────────────────────────────────────

        const float ShaftW       = 46f;
        const float ShaftGap     = 12f;
        const int   MaxTiles     = 9;
        const float MinFH        = 40f;
        const float MaxFH        = 86f;
        const float MinTileH     = 13f;
        const float MaxTileH     = 22f;
        const float AsideW       = 336f;
        const float HeaderH      = 50f;
        const float FooterH      = 64f;
        const float GutterW      = 54f;
        const float SectionPadX  = 18f;
        const float SectionPadTop= 16f;

        // resolved at build time
        float _fh;
        float _tileH;
        float _shaftsWidth;
        float _rightPad;
        float _sectionW;

        // ── Cached UI refs ─────────────────────────────────────────────────────

        // header
        TextMeshProUGUI _headerClock;
        TextMeshProUGUI _headerPattern;
        TextMeshProUGUI _headerStep;

        // reward
        TextMeshProUGUI _rewardTotal;
        TextMeshProUGUI _rewardDelta;

        // KPIs
        TextMeshProUGUI[] _kpiValues; // 6

        // util
        RectTransform[]  _utilFillRt;
        TextMeshProUGUI[] _utilPct;
        float            _utilTrackW;

        // floor bands (rebuilt on RebuildDynamicUI)
        struct FloorBandUI
        {
            public Image upCallImg;
            public Image downCallImg;
            public Transform upTrack;
            public Transform downTrack;
        }
        FloorBandUI[] _floors;

        // queue bars
        struct QueueRowUI
        {
            public RectTransform upBar;
            public RectTransform dnBar;
            public TextMeshProUGUI counts;
        }
        QueueRowUI[] _qrows;
        float _queueTrackW;

        // elevator cars (rebuilt on RebuildDynamicUI)
        struct CarUI
        {
            public RectTransform carRect;
            public Image         border;
            public Image         doorStrip;
            public TextMeshProUGUI loadLabel;
            public Transform     dotsParent;
            public Image         dirTriangle;
        }
        CarUI[] _cars;

        // observation
        TextMeshProUGUI _obsLocations;
        TextMeshProUGUI _obsButtons;
        TextMeshProUGUI _obsHall;
        GameObject      _obsBlock;

        // footer
        Button   _playBtn;
        TextMeshProUGUI _playBtnLabel;
        Button   _stepBtn;
        Slider   _speedSlider;
        TextMeshProUGUI _speedLabel;
        Slider   _trafficSlider;
        TextMeshProUGUI _trafficLabel;
        TMP_Dropdown _patternDropdown;
        Button   _dayCycleBtn;
        TextMeshProUGUI _dayCycleBtnLabel;
        TMP_Dropdown _floorsDropdown;
        TMP_Dropdown _carsDropdown;
        TMP_Dropdown _capDropdown;

        // dynamic container refs (for RebuildDynamicUI)
        Transform _buildingBandsParent;
        Transform _buildingShaftsParent;
        Transform _asideUtilRows;
        Transform _asideQueueRows;

        // Sprites for direction triangles and dots
        Sprite _circleSprite;
        Sprite _triangleUpSprite;
        Sprite _triangleDownSprite;

        readonly StringBuilder _sb = new StringBuilder(256);

        // ── Color shortcuts ────────────────────────────────────────────────────

        Color Void         => CKColor.Void;
        Color Surface      => CKColor.Surface;
        Color Raised       => CKColor.Raised;
        Color Border       => CKColor.Border;
        Color TextBright   => CKColor.TextBright;
        Color TextPrimary  => CKColor.TextPrimary;
        Color TextSecondary=> CKColor.TextSecondary;
        Color TextMuted    => CKColor.TextMuted;
        Color Amber        => CKColor.Amber;
        Color AmberBright  => CKColor.AmberBright;
        Color Coral        => CKColor.Coral;
        Color CoralBright  => CKColor.CoralBright;
        Color Steel        => CKColor.Steel;
        Color SteelBright  => CKColor.SteelBright;
        Color Sage         => CKColor.Sage;

        // ── Lifecycle ─────────────────────────────────────────────────────────

        void Start()
        {
            BuildSprites();
            BuildSim();
            if (uiRoot == null)
                uiRoot = (transform.parent != null ? transform.parent : transform) as RectTransform
                         ?? GetComponentInParent<Canvas>()?.GetComponent<RectTransform>();
            BuildUI();
        }

        void Update()
        {
            if (_playing)
            {
                Advance(Time.deltaTime * speed);
                RefreshView();
            }
        }

        // ── Simulation ────────────────────────────────────────────────────────

        void BuildSim()
        {
            _cfg     = buildingConfigAsset    ? Instantiate(buildingConfigAsset)    : ScriptableObject.CreateInstance<BuildingConfig>();
            _reward  = rewardConfigAsset      ? Instantiate(rewardConfigAsset)      : ScriptableObject.CreateInstance<RewardConfig>();
            _obs     = observationConfigAsset ? Instantiate(observationConfigAsset) : ScriptableObject.CreateInstance<ObservationConfig>();
            _traffic = trafficConfigAsset     ? Instantiate(trafficConfigAsset)     : ScriptableObject.CreateInstance<TrafficConfig>();

            _cfg.numFloors    = startFloors;
            _cfg.numElevators = startCars;
            _cfg.capacity     = startCapacity;
            _cfg.randomizeActive          = false;
            _cfg.serviceChangeProbability = 0f;
            _cfg.minActiveElevators       = 1;
            _traffic.useDayCycle     = false;
            _traffic.defaultPattern  = startPattern;
            _traffic.intensity       = intensity;
            _selectedPattern         = startPattern;

            _b            = new Building(_cfg, _reward, _obs, _traffic, seed);
            _b.Reset();
            _decisions    = 0;
            _total        = 0;
            _last         = 0;
            _utilSum      = new float[_cfg.numElevators];
            _utilSteps    = 0;
            _decisionClock= 0;
        }

        void Advance(float simDelta)
        {
            const float MaxSub = 0.05f;
            while (simDelta > 1e-6f)
            {
                float h = Mathf.Min(MaxSub, simDelta);
                _b.Tick(h);
                simDelta -= h;
                _decisionClock += h;
                if (_decisionClock >= _cfg.decisionInterval)
                {
                    _decisionClock -= _cfg.decisionInterval;
                    Decide();
                }
            }
        }

        void Decide()
        {
            _traffic.defaultPattern = ActivePattern();
            var act = ElevatorHeuristics.CollectiveLook(_b);
            for (int i = 0; i < _cfg.numElevators; i++)
                _b.ApplyAction(i, act[i]);
            _last  = _b.CollectReward();
            _total += _last;
            for (int i = 0; i < _cfg.numElevators; i++)
                _utilSum[i] += _b.cars[i].Load;
            _utilSteps++;
            _decisions++;
        }

        void StepOnce()
        {
            if (_playing) return;
            int  d     = _decisions;
            int  guard = 0;
            while (_decisions == d && guard++ < 100000)
                Advance(0.05f);
            RefreshView();
        }

        const int MinutesPerStep = 2;

        TrafficPattern ActivePattern()
        {
            if (!_dayCycle) return _selectedPattern;
            int   m = (6 * 60 + _decisions * MinutesPerStep) % 1440;
            float h = m / 60f;
            if (h >= 6  && h < 10) return TrafficPattern.UpPeak;
            if (h >= 11 && h < 14) return TrafficPattern.Lunch;
            if (h >= 16 && h < 19) return TrafficPattern.DownPeak;
            return TrafficPattern.Midday;
        }

        string Clock()
        {
            int m = (6 * 60 + _decisions * MinutesPerStep) % 1440;
            return $"{m / 60:00}:{m % 60:00}";
        }

        string PatternLabel(TrafficPattern p) => p switch
        {
            TrafficPattern.UpPeak   => "UP-PEAK",
            TrafficPattern.DownPeak => "DN-PEAK",
            TrafficPattern.Lunch    => "LUNCH",
            TrafficPattern.Midday   => "MIDDAY",
            TrafficPattern.Uniform  => "UNIFORM",
            _ => "?"
        };

        // ── Sprite construction ───────────────────────────────────────────────

        void BuildSprites()
        {
            // Dots and direction indicators are just colored squares; no special sprite needed.
            _circleSprite       = null;
            _triangleUpSprite   = null;
            _triangleDownSprite = null;
        }

        // ── Layout resolution ─────────────────────────────────────────────────

        void ResolveLayout()
        {
            // Reference resolution 1280x800, aside=336, header=50, footer=64
            _sectionW    = 1280f - AsideW - SectionPadX * 2f;
            float mainH  = 800f - HeaderH - FooterH - SectionPadTop * 2f;
            _fh          = Mathf.Clamp(Mathf.Floor(mainH / _cfg.numFloors), MinFH, MaxFH);
            _tileH       = Mathf.Clamp(Mathf.Floor((_fh - 16f) / 2f) - 1f, MinTileH, MaxTileH);
            _shaftsWidth = _cfg.numElevators * ShaftW + (_cfg.numElevators - 1) * ShaftGap;
            _rightPad    = _shaftsWidth + 30f;
        }

        // ── UI BUILD ──────────────────────────────────────────────────────────

        void BuildUI()
        {
            ResolveLayout();

            // Use THIS GameObject's RectTransform as the actual build root
            var rt = GetComponent<RectTransform>();
            if (rt == null) rt = gameObject.AddComponent<RectTransform>();
            var buildRoot = rt;

            // Clear any previous UI children (only children of THIS rect, not siblings)
            for (int i = buildRoot.childCount - 1; i >= 0; i--)
                Destroy(buildRoot.GetChild(i).gameObject);

            // Root bg
            var rootImg = buildRoot.gameObject.GetComponent<Image>();
            if (rootImg == null) rootImg = buildRoot.gameObject.AddComponent<Image>();
            rootImg.color = Void;
            rootImg.raycastTarget = false;

            // reassign uiRoot to this object so sub-methods use the right parent
            uiRoot = buildRoot;

            BuildHeader(uiRoot);
            BuildFooter(uiRoot);
            BuildMain(uiRoot);

            RefreshView();
            UpdateFooterState();
        }

        void BuildHeader(Transform root)
        {
            var rt = CKUI.Panel(root, "Header", Surface);
            CKUI.AnchorTop(rt, HeaderH);
            CKUI.BorderBottom(rt, Border);

            // Left: ELEVATOR + subtitle
            var left = CKUI.EmptyRect(rt, "Left");
            left.anchorMin = new Vector2(0, 0);
            left.anchorMax = new Vector2(0.5f, 1f);
            left.offsetMin = new Vector2(18, 0);
            left.offsetMax = Vector2.zero;
            var hGroup = left.gameObject.AddComponent<HorizontalLayoutGroup>();
            hGroup.spacing = 12;
            hGroup.childAlignment = TextAnchor.MiddleLeft;
            hGroup.childForceExpandWidth = false;
            hGroup.childForceExpandHeight = false;

            var title = CKUI.Label(left, "Title", "ELEVATOR", displayFont, 19, TextBright,
                TextAlignmentOptions.MidlineLeft, 5f);
            title.fontStyle = FontStyles.Bold;
            var ttle = title.gameObject.AddComponent<LayoutElement>();
            ttle.flexibleWidth = 0;

            var sub = CKUI.Label(left, "Sub", "RL CONTROL SANDBOX", monoFont, 11, TextMuted,
                TextAlignmentOptions.MidlineLeft, 18f);
            sub.fontStyle = FontStyles.UpperCase;
            var sle = sub.gameObject.AddComponent<LayoutElement>();
            sle.flexibleWidth = 0;

            // Right: SIM TIME | PATTERN | STEP
            var right = CKUI.EmptyRect(rt, "Right");
            right.anchorMin = new Vector2(0.5f, 0f);
            right.anchorMax = Vector2.one;
            right.offsetMin = Vector2.zero;
            right.offsetMax = new Vector2(-18, 0);
            var rGroup = right.gameObject.AddComponent<HorizontalLayoutGroup>();
            rGroup.spacing = 26;
            rGroup.childAlignment = TextAnchor.MiddleRight;
            rGroup.childForceExpandWidth = false;
            rGroup.childForceExpandHeight = false;
            rGroup.reverseArrangement = false;

            _headerClock   = BuildHeaderStat(right, "SIM TIME", "06:00", TextPrimary);
            _headerPattern = BuildHeaderStat(right, "PATTERN",  "UP-PEAK", Amber);
            _headerStep    = BuildHeaderStat(right, "STEP",     "0",       TextPrimary);
        }

        TextMeshProUGUI BuildHeaderStat(Transform parent, string lbl, string val, Color valColor)
        {
            var col = CKUI.EmptyRect(parent, lbl);
            col.gameObject.AddComponent<LayoutElement>().flexibleWidth = 0;
            var vg = col.gameObject.AddComponent<VerticalLayoutGroup>();
            vg.spacing = 1;
            vg.childAlignment = TextAnchor.MiddleRight;
            vg.childForceExpandWidth = false;
            vg.childForceExpandHeight = false;

            CKUI.Label(col, "Lbl", lbl, monoFont, 10, TextMuted,
                TextAlignmentOptions.Right, 18f).fontStyle = FontStyles.UpperCase;
            var valTmp = CKUI.Label(col, "Val", val, monoFont, 15, valColor,
                TextAlignmentOptions.Right);
            return valTmp;
        }

        void BuildFooter(Transform root)
        {
            var rt = CKUI.Panel(root, "Footer", Surface);
            CKUI.AnchorBottom(rt, FooterH);
            CKUI.BorderTop(rt, Border);

            var hGroup = rt.gameObject.AddComponent<HorizontalLayoutGroup>();
            hGroup.padding = new RectOffset(18, 18, 0, 0);
            hGroup.spacing = 12;
            hGroup.childAlignment = TextAnchor.MiddleLeft;
            hGroup.childForceExpandWidth = false;
            hGroup.childForceExpandHeight = true; // makes buttons fill full 64px height → clickable

            // PLAY
            _playBtn = CKUI.MakeButton(rt, "PlayBtn", "PLAY", monoFont, 12,
                Amber, Void, 74);
            _playBtnLabel = _playBtn.GetComponentInChildren<TextMeshProUGUI>();

            // STEP
            _stepBtn = CKUI.MakeButton(rt, "StepBtn", "STEP", monoFont, 12,
                Raised, TextPrimary, 60);
            AddBorder1px(_stepBtn.GetComponent<RectTransform>(), Border);

            // RESET
            var resetBtn = CKUI.MakeButton(rt, "ResetBtn", "RESET", monoFont, 12,
                Raised, TextPrimary, 60);
            AddBorder1px(resetBtn.GetComponent<RectTransform>(), Border);

            // divider
            BuildVDivider(rt);

            // SPEED
            var speedGroup = BuildLabeledControl(rt, "SPEED");
            _speedLabel = CKUI.Label(speedGroup, "Val", $"{speed}/s", monoFont, 11, Amber,
                TextAlignmentOptions.MidlineLeft);
            _speedLabel.gameObject.AddComponent<LayoutElement>().minWidth = 36;
            _speedSlider = CKUI.MakeSlider(speedGroup, "SpeedSlider", 1, 20, speed, true,
                Raised, Amber);
            SetSliderSize(_speedSlider.GetComponent<RectTransform>(), 80);

            // TRAFFIC
            var trafficGroup = BuildLabeledControl(rt, "TRAFFIC");
            _trafficLabel = CKUI.Label(trafficGroup, "Val", $"{intensity:F1}×", monoFont, 11, Amber,
                TextAlignmentOptions.MidlineLeft);
            _trafficLabel.gameObject.AddComponent<LayoutElement>().minWidth = 36;
            _trafficSlider = CKUI.MakeSlider(trafficGroup, "TrafficSlider", 0, 3, intensity, false,
                Raised, Amber);
            SetSliderSize(_trafficSlider.GetComponent<RectTransform>(), 80);

            // PATTERN
            BuildFooterLabel(rt, "PATTERN");
            _patternDropdown = BuildTMPDropdown(rt, "PatternDrop",
                new[] { "Up-peak", "Down-peak", "Lunch", "Midday", "Uniform" }, 80);

            // DAY CYCLE
            _dayCycleBtn = CKUI.MakeButton(rt, "DayCycleBtn", "DAY CYCLE  OFF", monoFont, 11,
                Raised, TextMuted, 100);
            _dayCycleBtnLabel = _dayCycleBtn.GetComponentInChildren<TextMeshProUGUI>();
            AddBorder1px(_dayCycleBtn.GetComponent<RectTransform>(), Border);

            BuildVDivider(rt);

            // FLOORS
            BuildFooterLabel(rt, "FLOORS");
            _floorsDropdown = BuildTMPDropdown(rt, "FloorsDrop", FloorOptions(), 56);

            // CARS
            BuildFooterLabel(rt, "CARS");
            _carsDropdown = BuildTMPDropdown(rt, "CarsDrop",
                new[] { "1","2","3","4","5","6" }, 46);

            // CAPACITY
            BuildFooterLabel(rt, "CAP");
            _capDropdown = BuildTMPDropdown(rt, "CapDrop",
                new[] { "4","6","8","10","12","16" }, 46);

            // ── Set initial dropdown values BEFORE wiring listeners ──
            // Setting .value after listeners are added fires onValueChanged, causing
            // RebuildDynamicUI → BuildUI → BuildFooter → set value → infinite loop.
            _floorsDropdown.SetValueWithoutNotify(startFloors - 3);
            _carsDropdown.SetValueWithoutNotify(startCars - 1);
            _capDropdown.SetValueWithoutNotify(CapIndex(startCapacity));
            _patternDropdown.SetValueWithoutNotify((int)startPattern);

            // ── Wire up callbacks ──
            _playBtn.onClick.AddListener(() =>
            {
                _playing = !_playing;
                UpdateFooterState();
                RefreshView();
            });
            _stepBtn.onClick.AddListener(StepOnce);
            resetBtn.onClick.AddListener(() => { _playing = false; BuildSim(); RebuildDynamicUI(); });

            _speedSlider.onValueChanged.AddListener(v =>
            {
                speed = Mathf.RoundToInt(v);
                _speedLabel.text = $"{speed}/s";
            });
            _trafficSlider.onValueChanged.AddListener(v =>
            {
                intensity = v;
                _traffic.intensity = v;
                _trafficLabel.text = $"{v:F1}×";
            });
            _patternDropdown.onValueChanged.AddListener(i =>
            {
                _selectedPattern = (TrafficPattern)i;
            });
            _dayCycleBtn.onClick.AddListener(() =>
            {
                _dayCycle = !_dayCycle;
                _patternDropdown.interactable = !_dayCycle;
                var alpha = _dayCycle ? 1f : 0.4f;
                var c = _patternDropdown.GetComponent<Image>();
                if (c) c.color = new Color(c.color.r, c.color.g, c.color.b, alpha);
                UpdateFooterState();
            });
            _floorsDropdown.onValueChanged.AddListener(i =>
            {
                startFloors = i + 3;
                _cfg.numFloors = startFloors;
                BuildSim();
                RebuildDynamicUI();
            });
            _carsDropdown.onValueChanged.AddListener(i =>
            {
                startCars = i + 1;
                _cfg.numElevators = startCars;
                BuildSim();
                RebuildDynamicUI();
            });
            _capDropdown.onValueChanged.AddListener(i =>
            {
                startCapacity = new[] { 4, 6, 8, 10, 12, 16 }[i];
                _cfg.capacity = startCapacity;
                BuildSim();
            });
        }

        Transform BuildLabeledControl(Transform parent, string label)
        {
            var group = CKUI.EmptyRect(parent, label + "Group");
            group.gameObject.AddComponent<LayoutElement>().flexibleWidth = 0;
            var hg = group.gameObject.AddComponent<HorizontalLayoutGroup>();
            hg.spacing = 6;
            hg.childAlignment = TextAnchor.MiddleLeft;
            hg.childForceExpandWidth = false;
            hg.childForceExpandHeight = true; // fills parent's 64px footer height

            var lbl = CKUI.Label(group, "Lbl", label, monoFont, 9.5f, TextMuted,
                TextAlignmentOptions.MidlineLeft, 14f);
            lbl.fontStyle = FontStyles.UpperCase;
            lbl.gameObject.AddComponent<LayoutElement>().flexibleWidth = 0;

            return group;
        }

        void BuildFooterLabel(Transform parent, string text)
        {
            var lbl = CKUI.Label(parent, text + "Lbl", text, monoFont, 9.5f, TextMuted,
                TextAlignmentOptions.MidlineLeft, 14f);
            lbl.fontStyle = FontStyles.UpperCase;
            lbl.gameObject.AddComponent<LayoutElement>().flexibleWidth = 0;
        }

        void BuildVDivider(Transform parent)
        {
            var rt = CKUI.Panel(parent, "VDiv", Border);
            var le = rt.gameObject.AddComponent<LayoutElement>();
            le.minWidth  = 1;
            le.minHeight = 32;
            le.flexibleWidth = 0;
        }

        void SetSliderSize(RectTransform rt, float width)
        {
            var le = rt.gameObject.AddComponent<LayoutElement>();
            le.minWidth    = width;
            le.preferredWidth = width;
            le.flexibleWidth = 0;
            le.minHeight   = 20;
        }

        TMP_Dropdown BuildTMPDropdown(Transform parent, string name, string[] options, float width)
        {
            var rt = CKUI.Panel(parent, name, Raised);
            var bgImg = rt.GetComponent<Image>();
            bgImg.raycastTarget = true; // required for dropdown to receive clicks
            AddBorder1px(rt, Border);
            var le = rt.gameObject.AddComponent<LayoutElement>();
            le.minWidth = width;
            le.preferredWidth = width;
            le.flexibleWidth = 0;

            var dd = rt.gameObject.AddComponent<TMP_Dropdown>();
            dd.captionText = CKUI.Label(rt, "Label", options[0], monoFont, 11, TextPrimary,
                TextAlignmentOptions.MidlineLeft);
            CKUI.Stretch(dd.captionText.rectTransform, 4, 16, 2, 2);

            // arrow image
            var arrow = CKUI.Box(rt, "Arrow", TextMuted);
            arrow.rectTransform.anchorMin = new Vector2(1, 0.5f);
            arrow.rectTransform.anchorMax = new Vector2(1, 0.5f);
            arrow.rectTransform.pivot     = new Vector2(1, 0.5f);
            arrow.rectTransform.anchoredPosition = new Vector2(-4, 0);
            arrow.rectTransform.sizeDelta = new Vector2(8, 6);
            dd.image = bgImg;

            // template (pass width explicitly; parent.sizeDelta is 0 until layout runs)
            var template = BuildDropdownTemplate(rt, options, width);
            dd.template  = template;

            var itemOpts = new List<TMP_Dropdown.OptionData>();
            foreach (var o in options) itemOpts.Add(new TMP_Dropdown.OptionData(o));
            dd.options = itemOpts;

            return dd;
        }

        RectTransform BuildDropdownTemplate(RectTransform parent, string[] options, float width)
        {
            var template = CKUI.Panel(parent, "Template", Surface);
            template.gameObject.AddComponent<ScrollRect>();
            // Anchor to parent top-left, open upward (pivot bottom-left, y offset = 0)
            // so the list appears above the footer instead of going below the screen edge.
            template.anchorMin = new Vector2(0, 1);
            template.anchorMax = new Vector2(0, 1);
            template.pivot     = new Vector2(0, 0);   // bottom-left pivot → extends upward
            template.anchoredPosition = Vector2.zero;
            template.sizeDelta = new Vector2(width, options.Length * 24 + 4);
            AddBorder1px(template, Border);
            template.gameObject.SetActive(false);

            var viewport = CKUI.EmptyRect(template, "Viewport");
            CKUI.Stretch(viewport.GetComponent<RectTransform>(), 0, 0, 2, 2);
            viewport.gameObject.AddComponent<Mask>().showMaskGraphic = false;
            viewport.gameObject.AddComponent<Image>().color = Color.clear;

            var content = CKUI.EmptyRect(viewport, "Content");
            content.anchorMin = new Vector2(0, 1);
            content.anchorMax = Vector2.one;
            content.pivot = new Vector2(0.5f, 1f);
            content.offsetMin = Vector2.zero;
            content.offsetMax = Vector2.zero;
            content.sizeDelta = new Vector2(0, options.Length * 24);

            var item = CKUI.Panel(content, "Item", Color.clear);
            item.sizeDelta = new Vector2(0, 24);
            item.anchorMin = new Vector2(0, 1);
            item.anchorMax = new Vector2(1, 1);
            item.pivot = new Vector2(0.5f, 1f);
            item.anchoredPosition = Vector2.zero;

            var toggle = item.gameObject.AddComponent<Toggle>();
            toggle.targetGraphic = item.GetComponent<Image>();

            var itemBg = CKUI.Box(item, "Item Background", Raised);
            CKUI.Stretch(itemBg.rectTransform);

            var checkmark = CKUI.Box(item, "Item Checkmark", Amber);
            checkmark.rectTransform.anchorMin = new Vector2(0, 0.5f);
            checkmark.rectTransform.anchorMax = new Vector2(0, 0.5f);
            checkmark.rectTransform.pivot = new Vector2(0, 0.5f);
            checkmark.rectTransform.anchoredPosition = new Vector2(2, 0);
            checkmark.rectTransform.sizeDelta = new Vector2(3, 12);

            var itemLabel = CKUI.Label(item, "Item Label", "", monoFont, 11, TextPrimary,
                TextAlignmentOptions.MidlineLeft);
            CKUI.Stretch(itemLabel.rectTransform, 10, 2, 0, 0);

            toggle.graphic = checkmark;
            // TMP_Dropdown looks for the item label via the Toggle's GameObject
            // We need to also set the scrollrect references
            var scroll = template.GetComponent<ScrollRect>();
            scroll.content  = content;
            scroll.viewport = viewport.GetComponent<RectTransform>();
            scroll.horizontal = false;

            return template;
        }

        void BuildMain(Transform root)
        {
            var rt = CKUI.EmptyRect(root, "Main");
            CKUI.AnchorMiddle(rt, HeaderH, FooterH);

            // Section (left, fills remaining width)
            var section = CKUI.Panel(rt, "Section", Void);
            CKUI.AnchorLeft(section, AsideW + 1); // +1 for the aside border

            // inner scroll content
            var inner = CKUI.EmptyRect(section, "BuildingContent");
            inner.anchorMin = new Vector2(0, 1);
            inner.anchorMax = new Vector2(1, 1);
            inner.pivot = new Vector2(0, 1);
            inner.anchoredPosition = new Vector2(SectionPadX, -SectionPadTop);
            inner.sizeDelta = new Vector2(-(SectionPadX * 2), _cfg.numFloors * _fh);

            // Floor bands parent (will be rebuilt)
            _buildingBandsParent  = inner;
            // Shafts parent
            _buildingShaftsParent = inner;

            BuildFloorBands(inner);
            BuildShafts(inner);

            // Aside (right)
            var aside = CKUI.Panel(rt, "Aside", Surface);
            CKUI.AnchorRight(aside, AsideW);
            CKUI.BorderLeft(aside, Border);

            BuildAside(aside);
        }

        // ── Building view ─────────────────────────────────────────────────────

        void BuildFloorBands(Transform parent)
        {
            int NF = _cfg.numFloors;
            _floors = new FloorBandUI[NF];

            for (int f = 0; f < NF; f++)
            {
                int fi    = f; // capture
                float top = (NF - 1 - f) * _fh;

                var band = CKUI.Panel(parent, $"Band{f}", Void);
                CKUI.TopLeft(band, 0, top, _sectionW - _rightPad, _fh);
                CKUI.BorderTop(band, Border);

                // Gutter (w54)
                var gutter = CKUI.Panel(band, "Gutter", Void);
                gutter.anchorMin = new Vector2(0, 0);
                gutter.anchorMax = new Vector2(0, 1);
                gutter.offsetMin = Vector2.zero;
                gutter.offsetMax = new Vector2(GutterW, 0);
                CKUI.BorderRight(gutter, Border);

                // Floor label
                string flabelText = f == 0 ? "G" : f.ToString();
                var flabel = CKUI.Label(gutter, "FloorLbl", flabelText, monoFont, 14, TextPrimary,
                    TextAlignmentOptions.Midline);
                CKUI.Stretch(flabel.rectTransform, 0, 0, 0, 14);

                // Call arrows (small rects as triangle stand-ins)
                var arrowRow = CKUI.EmptyRect(gutter, "Arrows");
                arrowRow.anchorMin = new Vector2(0, 0);
                arrowRow.anchorMax = new Vector2(1, 0);
                arrowRow.offsetMin = Vector2.zero;
                arrowRow.offsetMax = new Vector2(0, 14);
                var arrowHG = arrowRow.gameObject.AddComponent<HorizontalLayoutGroup>();
                arrowHG.spacing = 5;
                arrowHG.childAlignment = TextAnchor.MiddleCenter;
                arrowHG.childForceExpandWidth = arrowHG.childForceExpandHeight = false;

                var upImg   = MakeArrow(arrowRow, "Up",   true);
                var downImg = MakeArrow(arrowRow, "Down", false);

                _floors[f] = new FloorBandUI
                {
                    upCallImg   = upImg,
                    downCallImg = downImg,
                    upTrack     = BuildTrackRow(band, "UpTrack",   top),
                    downTrack   = BuildTrackRow(band, "DownTrack", top),
                };
            }
        }

        Image MakeArrow(Transform parent, string name, bool up)
        {
            var go  = new GameObject(name);
            go.transform.SetParent(parent, false);
            var img = go.AddComponent<Image>();
            img.color = new Color(TextMuted.r, TextMuted.g, TextMuted.b, 0.3f);
            img.raycastTarget = false;
            var le = go.AddComponent<LayoutElement>();
            le.minWidth = 8; le.minHeight = 8;
            le.flexibleWidth = le.flexibleHeight = 0;
            return img;
        }

        Transform BuildTrackRow(Transform band, string name, float bandTop)
        {
            // two rows stacked inside track area (x54..bandRight, centered vertically)
            // We just return a container; tiles are added at RefreshView
            var track = CKUI.EmptyRect(band, name);
            track.anchorMin = new Vector2(0, 0.5f);
            track.anchorMax = new Vector2(1, 0.5f);
            track.pivot = new Vector2(0, 0.5f);
            float rowH = _tileH;
            bool isUp = name == "UpTrack";
            track.offsetMin = new Vector2(GutterW + 10, isUp ? 2.5f  : -(rowH + 2.5f));
            track.offsetMax = new Vector2(-10,           isUp ? rowH + 2.5f : -2.5f);

            var hg = track.gameObject.AddComponent<HorizontalLayoutGroup>();
            hg.spacing = 2;
            hg.childAlignment = TextAnchor.MiddleLeft;
            hg.childForceExpandWidth = hg.childForceExpandHeight = false;

            return track;
        }

        void BuildShafts(Transform parent)
        {
            int NF = _cfg.numFloors;
            int NE = _cfg.numElevators;
            _cars = new CarUI[NE];

            float shaftsX = _sectionW - _rightPad;

            var shaftsContainer = CKUI.EmptyRect(parent, "Shafts");
            CKUI.TopLeft(shaftsContainer, shaftsX, 0, _shaftsWidth, NF * _fh);

            for (int i = 0; i < NE; i++)
            {
                float sx = i * (ShaftW + ShaftGap);

                var shaft = CKUI.Panel(shaftsContainer, $"Shaft{i}", Surface);
                CKUI.TopLeft(shaft, sx, 0, ShaftW, NF * _fh);
                AddBorder1px(shaft, Border);

                // floor grid lines
                for (int k = 1; k < NF; k++)
                {
                    var line = CKUI.Box(shaft, $"FLine{k}", new Color(Border.r, Border.g, Border.b, 0.4f));
                    var lrt = line.rectTransform;
                    lrt.anchorMin = new Vector2(0, 0);
                    lrt.anchorMax = new Vector2(1, 0);
                    lrt.pivot = new Vector2(0.5f, 0);
                    lrt.anchoredPosition = new Vector2(0, k * _fh);
                    lrt.sizeDelta = new Vector2(0, 1);
                }

                // shaft id label
                var idLabel = CKUI.Label(shaft, "ID", $"E{i}", monoFont, 9, TextMuted,
                    TextAlignmentOptions.Top, 12f);
                var idrt = idLabel.rectTransform;
                idrt.anchorMin = new Vector2(0, 1);
                idrt.anchorMax = new Vector2(1, 1);
                idrt.pivot = new Vector2(0.5f, 1);
                idrt.anchoredPosition = new Vector2(0, -3);
                idrt.sizeDelta = new Vector2(0, 14);

                _cars[i] = BuildCar(shaft, i, NF);
            }
        }

        CarUI BuildCar(Transform shaft, int index, int NF)
        {
            var carRt = CKUI.Panel(shaft, $"Car{index}", Raised);
            // initial position at floor 0
            float carY = (NF - 1 - 0) * _fh + 4;
            CKUI.TopLeft(carRt, 3, carY, ShaftW - 6, _fh - 8);
            AddBorder1px(carRt, Amber);
            var border = carRt.GetComponent<Image>();

            // door strip (left edge, 3px wide)
            var door = CKUI.Box(carRt, "DoorStrip", AmberBright);
            door.rectTransform.anchorMin = new Vector2(0, 0);
            door.rectTransform.anchorMax = new Vector2(0, 1);
            door.rectTransform.offsetMin = Vector2.zero;
            door.rectTransform.offsetMax = new Vector2(3, 0);
            door.gameObject.SetActive(false);

            // inner layout
            var inner = CKUI.EmptyRect(carRt, "Inner");
            CKUI.Stretch(inner, 4, 4, 4, 4);
            var vg = inner.gameObject.AddComponent<VerticalLayoutGroup>();
            vg.spacing = 2;
            vg.childAlignment = TextAnchor.UpperCenter;
            vg.childForceExpandWidth = false;
            vg.childForceExpandHeight = false;

            var loadLbl = CKUI.Label(inner, "Load", "0/8", monoFont, 12, AmberBright,
                TextAlignmentOptions.Midline);
            loadLbl.gameObject.AddComponent<LayoutElement>().flexibleWidth = 0;

            var dotsParent = CKUI.EmptyRect(inner, "Dots");
            var dotsHG = dotsParent.gameObject.AddComponent<HorizontalLayoutGroup>();
            dotsHG.spacing = 2;
            dotsHG.childAlignment = TextAnchor.MiddleCenter;
            dotsHG.childForceExpandWidth = dotsHG.childForceExpandHeight = false;
            dotsParent.gameObject.AddComponent<LayoutElement>().flexibleWidth = 0;

            var dirImg = CKUI.Box(inner, "Dir", Amber);
            dirImg.rectTransform.sizeDelta = new Vector2(8, 8);
            dirImg.gameObject.AddComponent<LayoutElement>().flexibleWidth = 0;

            return new CarUI
            {
                carRect    = carRt,
                border     = border,
                doorStrip  = door,
                loadLabel  = loadLbl,
                dotsParent = dotsParent,
                dirTriangle = dirImg,
            };
        }

        // ── Aside / metrics ───────────────────────────────────────────────────

        void BuildAside(Transform aside)
        {
            var vg = aside.gameObject.AddComponent<VerticalLayoutGroup>();
            vg.childForceExpandWidth  = true;
            vg.childForceExpandHeight = false;

            BuildRewardBlock(aside);
            BuildKPIBlock(aside);
            BuildUtilBlock(aside);
            BuildQueueBlock(aside);
            if (showObservation) BuildObsBlock(aside);
        }

        void BuildRewardBlock(Transform parent)
        {
            var rt = CKUI.Panel(parent, "RewardBlock", Surface);
            rt.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
            CKUI.BorderBottom(rt, Border);
            var vg = rt.gameObject.AddComponent<VerticalLayoutGroup>();
            vg.padding = new RectOffset(20, 20, 18, 16);
            vg.childForceExpandWidth = false;
            vg.childForceExpandHeight = false;
            vg.spacing = 6;

            var lbl = CKUI.Label(rt, "Lbl", "CUMULATIVE REWARD", monoFont, 10, TextMuted,
                TextAlignmentOptions.MidlineLeft, 18f);
            lbl.fontStyle = FontStyles.UpperCase;
            lbl.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;

            var row = CKUI.EmptyRect(rt, "Row");
            row.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
            var hg = row.gameObject.AddComponent<HorizontalLayoutGroup>();
            hg.spacing = 12;
            hg.childAlignment = TextAnchor.LowerLeft;
            hg.childForceExpandWidth = hg.childForceExpandHeight = false;

            _rewardTotal = CKUI.Label(row, "Total", "0.0", displayFont, 42, AmberBright,
                TextAlignmentOptions.MidlineLeft);
            _rewardTotal.fontStyle = FontStyles.Bold;
            _rewardTotal.gameObject.AddComponent<LayoutElement>().flexibleWidth = 0;

            _rewardDelta = CKUI.Label(row, "Delta", "+0.00 / step", monoFont, 13, AmberBright,
                TextAlignmentOptions.MidlineLeft);
            _rewardDelta.gameObject.AddComponent<LayoutElement>().flexibleWidth = 0;
        }

        void BuildKPIBlock(Transform parent)
        {
            var rt = CKUI.Panel(parent, "KPIBlock", Surface);
            rt.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
            CKUI.BorderBottom(rt, Border);

            var grid = rt.gameObject.AddComponent<GridLayoutGroup>();
            grid.cellSize = new Vector2(AsideW / 3f, 62);
            grid.spacing = Vector2.zero;
            grid.startCorner = GridLayoutGroup.Corner.UpperLeft;
            grid.startAxis = GridLayoutGroup.Axis.Horizontal;
            grid.childAlignment = TextAnchor.UpperLeft;
            grid.constraint = GridLayoutGroup.Constraint.FixedColumnCount;
            grid.constraintCount = 3;

            string[] kpiLabels = { "DELIVERED", "THRU/STEP", "AVG WAIT", "MAX WAIT", "REJECTED", "ABANDONED" };
            _kpiValues = new TextMeshProUGUI[6];
            for (int k = 0; k < 6; k++)
            {
                int ki = k;
                var cell = CKUI.Panel(rt, $"KPI{k}", Surface);
                bool rightBorder = k % 3 != 2;
                bool topBorder   = k >= 3;
                if (rightBorder) CKUI.BorderRight(cell, Border);
                if (topBorder)   CKUI.BorderTop(cell, Border);
                var cvg = cell.gameObject.AddComponent<VerticalLayoutGroup>();
                cvg.padding = new RectOffset(14, 14, 14, 12);
                cvg.childForceExpandWidth = false;
                cvg.childForceExpandHeight = false;
                cvg.spacing = 4;

                var klbl = CKUI.Label(cell, "KLbl", kpiLabels[k], monoFont, 9.5f, TextMuted,
                    TextAlignmentOptions.MidlineLeft, 14f);
                klbl.fontStyle = FontStyles.UpperCase;
                klbl.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;

                _kpiValues[k] = CKUI.Label(cell, "KVal", "0", monoFont, 20, TextBright,
                    TextAlignmentOptions.MidlineLeft);
                _kpiValues[k].gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
            }
        }

        void BuildUtilBlock(Transform parent)
        {
            var rt = CKUI.Panel(parent, "UtilBlock", Surface);
            rt.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
            CKUI.BorderBottom(rt, Border);
            var vg = rt.gameObject.AddComponent<VerticalLayoutGroup>();
            vg.padding = new RectOffset(20, 20, 16, 16);
            vg.childForceExpandWidth = false;
            vg.childForceExpandHeight = false;
            vg.spacing = 9;

            var lbl = CKUI.Label(rt, "Lbl", "ELEVATOR UTILIZATION", monoFont, 10, TextMuted,
                TextAlignmentOptions.MidlineLeft, 18f);
            lbl.fontStyle = FontStyles.UpperCase;
            lbl.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;

            _asideUtilRows = rt;
            BuildUtilRows(rt);
        }

        void BuildUtilRows(Transform parent)
        {
            // Destroy old rows (skip the header label child)
            var toDestroy = new List<GameObject>();
            for (int i = 1; i < parent.childCount; i++) // skip index 0 = label
                toDestroy.Add(parent.GetChild(i).gameObject);
            foreach (var g in toDestroy) Destroy(g);

            int NE = _cfg.numElevators;
            _utilFillRt = new RectTransform[NE];
            _utilPct    = new TextMeshProUGUI[NE];

            for (int i = 0; i < NE; i++)
            {
                var row = CKUI.EmptyRect(parent, $"UtilRow{i}");
                row.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
                var hg = row.gameObject.AddComponent<HorizontalLayoutGroup>();
                hg.spacing = 10;
                hg.childAlignment = TextAnchor.MiddleLeft;
                hg.childForceExpandWidth = hg.childForceExpandHeight = false;

                var idLbl = CKUI.Label(row, "ID", $"E{i}", monoFont, 11, TextSecondary,
                    TextAlignmentOptions.MidlineLeft);
                idLbl.gameObject.AddComponent<LayoutElement>().minWidth = 22;

                var track = CKUI.Panel(row, "Track", Void);
                track.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
                AddBorder1px(track, Border);
                track.sizeDelta = new Vector2(0, 8);

                var fill = CKUI.Panel(track, "Fill", Amber);
                fill.anchorMin = new Vector2(0, 0);
                fill.anchorMax = new Vector2(0, 1);
                fill.offsetMin = Vector2.zero;
                fill.offsetMax = new Vector2(0, 0);
                _utilFillRt[i] = fill;
                _utilTrackW    = AsideW - 20 * 2 - 22 - 34 - 10 * 2; // approx fixed

                var pctLbl = CKUI.Label(row, "Pct", "0%", monoFont, 11, Amber,
                    TextAlignmentOptions.Right);
                pctLbl.gameObject.AddComponent<LayoutElement>().minWidth = 34;
                _utilPct[i] = pctLbl;
            }
        }

        void BuildQueueBlock(Transform parent)
        {
            var rt = CKUI.Panel(parent, "QueueBlock", Surface);
            rt.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
            CKUI.BorderBottom(rt, Border);
            var vg = rt.gameObject.AddComponent<VerticalLayoutGroup>();
            vg.padding = new RectOffset(20, 20, 16, 16);
            vg.childForceExpandWidth = false;
            vg.childForceExpandHeight = false;
            vg.spacing = 5;

            // header row
            var hdr = CKUI.EmptyRect(rt, "Header");
            hdr.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
            var hhg = hdr.gameObject.AddComponent<HorizontalLayoutGroup>();
            hhg.childForceExpandWidth = true;
            hhg.childForceExpandHeight = false;

            var hlbl = CKUI.Label(hdr, "Lbl", "QUEUE LENGTH / FLOOR", monoFont, 10, TextMuted,
                TextAlignmentOptions.MidlineLeft, 18f);
            hlbl.fontStyle = FontStyles.UpperCase;
            hlbl.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;

            var legend = CKUI.Label(hdr, "Legend", "▲up  ▼dn", monoFont, 9, TextMuted,
                TextAlignmentOptions.MidlineRight, 10f);
            legend.gameObject.AddComponent<LayoutElement>().flexibleWidth = 0;

            _asideQueueRows = rt;
            BuildQueueRows(rt);
        }

        void BuildQueueRows(Transform parent)
        {
            var toDestroy = new List<GameObject>();
            for (int i = 1; i < parent.childCount; i++)
                toDestroy.Add(parent.GetChild(i).gameObject);
            foreach (var g in toDestroy) Destroy(g);

            int NF = _cfg.numFloors;
            _qrows = new QueueRowUI[NF];

            for (int f = NF - 1; f >= 0; f--)
            {
                int fi  = NF - 1 - f; // display index
                var row = CKUI.EmptyRect(parent, $"QRow{f}");
                row.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
                var hg = row.gameObject.AddComponent<HorizontalLayoutGroup>();
                hg.spacing = 8;
                hg.childAlignment = TextAnchor.MiddleLeft;
                hg.childForceExpandWidth = hg.childForceExpandHeight = false;

                string qflbl = f == 0 ? "G" : f.ToString();
                var lbl = CKUI.Label(row, "Lbl", qflbl, monoFont, 10, TextSecondary,
                    TextAlignmentOptions.Right);
                lbl.gameObject.AddComponent<LayoutElement>().minWidth = 18;

                var bars = CKUI.EmptyRect(row, "Bars");
                bars.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
                var bvg = bars.gameObject.AddComponent<VerticalLayoutGroup>();
                bvg.spacing = 2;
                bvg.childForceExpandWidth = true;
                bvg.childForceExpandHeight = false;

                var upTrack = CKUI.Panel(bars, "UpTrack", Void);
                upTrack.gameObject.AddComponent<LayoutElement>().minHeight = 5;
                var upFill = CKUI.Panel(upTrack, "UpFill", Steel);
                upFill.anchorMin = Vector2.zero;
                upFill.anchorMax = new Vector2(0, 1);
                upFill.offsetMin = Vector2.zero;
                upFill.offsetMax = new Vector2(0, 0);

                var dnTrack = CKUI.Panel(bars, "DnTrack", Void);
                dnTrack.gameObject.AddComponent<LayoutElement>().minHeight = 5;
                var dnFill = CKUI.Panel(dnTrack, "DnFill", Sage);
                dnFill.anchorMin = Vector2.zero;
                dnFill.anchorMax = new Vector2(0, 1);
                dnFill.offsetMin = Vector2.zero;
                dnFill.offsetMax = new Vector2(0, 0);

                var countLbl = CKUI.Label(row, "Counts", "0/0", monoFont, 10, TextMuted,
                    TextAlignmentOptions.Right);
                countLbl.gameObject.AddComponent<LayoutElement>().minWidth = 30;

                _qrows[fi] = new QueueRowUI
                {
                    upBar  = upFill,
                    dnBar  = dnFill,
                    counts = countLbl,
                };

                _queueTrackW = AsideW - 20 * 2 - 18 - 30 - 8 * 2;
            }
        }

        void BuildObsBlock(Transform parent)
        {
            var rt = CKUI.Panel(parent, "ObsBlock", Surface);
            rt.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
            var vg = rt.gameObject.AddComponent<VerticalLayoutGroup>();
            vg.padding = new RectOffset(20, 20, 16, 22);
            vg.childForceExpandWidth = false;
            vg.childForceExpandHeight = false;
            vg.spacing = 6;
            _obsBlock = rt.gameObject;

            var lbl = CKUI.Label(rt, "Lbl", "OBSERVATION · LIMITED", monoFont, 10, TextMuted,
                TextAlignmentOptions.MidlineLeft, 18f);
            lbl.fontStyle = FontStyles.UpperCase;
            lbl.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;

            _obsLocations = CKUI.Label(rt, "Locations", "", monoFont, 12, SteelBright,
                TextAlignmentOptions.MidlineLeft);
            _obsLocations.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
            _obsLocations.enableWordWrapping = true;

            _obsButtons = CKUI.Label(rt, "CarBtn", "", monoFont, 11, Amber,
                TextAlignmentOptions.MidlineLeft);
            _obsButtons.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
            _obsButtons.enableWordWrapping = true;

            _obsHall = CKUI.Label(rt, "Hall", "", monoFont, 11, TextMuted,
                TextAlignmentOptions.MidlineLeft);
            _obsHall.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1;
            _obsHall.enableWordWrapping = true;
        }

        // ── Rebuild on config change ─────────────────────────────────────────

        void RebuildDynamicUI()
        {
            ResolveLayout();
            BuildUI(); // full rebuild is simplest; fast enough for editor-like config changes
        }

        // ── RefreshView ───────────────────────────────────────────────────────

        void RefreshView()
        {
            if (_b == null) return;

            // Header
            _headerClock.text   = Clock();
            _headerPattern.text = PatternLabel(ActivePattern());
            _headerStep.text    = _decisions.ToString();

            // Reward
            _rewardTotal.text = $"{_total:F1}";
            _rewardDelta.color = _last >= 0 ? AmberBright : SteelBright;
            string sign = _last >= 0 ? "+" : "";
            _rewardDelta.text = $"{sign}{_last:F2} / step";

            // KPIs
            float thruPerStep = _decisions > 0 ? (float)(_b.DeliveredTotal / (double)_decisions) : 0f;
            float avgWait     = _b.WaitCount > 0 ? _b.WaitSum / _b.WaitCount : 0f;
            _kpiValues[0].text = _b.DeliveredTotal.ToString();
            _kpiValues[1].text = $"{thruPerStep:F2}";
            _kpiValues[2].text = $"{avgWait:F1}";
            _kpiValues[3].text = Mathf.RoundToInt(_b.MaxWaitObserved).ToString();
            _kpiValues[4].text = _b.RejectedTotal.ToString();
            _kpiValues[5].text = _b.AbandonedTotal.ToString();

            // Utilization
            for (int i = 0; i < _cfg.numElevators && i < _utilFillRt.Length; i++)
            {
                float avg = _utilSteps > 0 ? _utilSum[i] / _utilSteps : 0f;
                float fillW = avg * _utilTrackW;
                _utilFillRt[i].offsetMax = new Vector2(fillW, 0);
                _utilPct[i].text = $"{avg * 100f:F0}%";
            }

            // Floor bands: call arrows + tiles
            int NF = _cfg.numFloors;
            for (int f = 0; f < NF && f < _floors.Length; f++)
            {
                var fu = _floors[f];
                bool upActive   = _b.upQ[f].Count > 0;
                bool downActive = _b.downQ[f].Count > 0;

                fu.upCallImg.color   = upActive
                    ? new Color(AmberBright.r, AmberBright.g, AmberBright.b, 1f)
                    : new Color(TextMuted.r, TextMuted.g, TextMuted.b, 0.3f);
                fu.downCallImg.color = downActive
                    ? new Color(AmberBright.r, AmberBright.g, AmberBright.b, 1f)
                    : new Color(TextMuted.r, TextMuted.g, TextMuted.b, 0.3f);

                RefreshTileRow(fu.upTrack,   _b.upQ[f],   true);
                RefreshTileRow(fu.downTrack, _b.downQ[f], false);
            }

            // Queue bars
            for (int f = NF - 1; f >= 0; f--)
            {
                int fi = NF - 1 - f;
                if (fi >= _qrows.Length) continue;
                var qr = _qrows[fi];
                int upCount = _b.upQ[f].Count;
                int dnCount = _b.downQ[f].Count;
                float upFrac = Mathf.Clamp01(upCount / (float)_cfg.maxQueue);
                float dnFrac = Mathf.Clamp01(dnCount / (float)_cfg.maxQueue);
                qr.upBar.offsetMax = new Vector2(upFrac * _queueTrackW, 0);
                qr.dnBar.offsetMax = new Vector2(dnFrac * _queueTrackW, 0);
                qr.counts.text = $"{upCount}/{dnCount}";
            }

            // Elevator cars
            for (int i = 0; i < _cfg.numElevators && i < _cars.Length; i++)
            {
                var car = _b.cars[i];
                var cui = _cars[i];

                bool doorOpen = car.state == CarState.DoorsOpening
                             || car.state == CarState.Dwelling
                             || car.state == CarState.DoorsClosing;

                // car position (top from top of shaft)
                float carTopFromShaftTop = (NF - 1 - car.position) * _fh + 4f;
                cui.carRect.anchoredPosition = new Vector2(3, -carTopFromShaftTop);

                cui.doorStrip.gameObject.SetActive(doorOpen);

                // border color
                Color borderCol = doorOpen ? AmberBright : Amber;
                cui.border.color = borderCol;

                // load label
                int riders  = car.riders.Count;
                int cap     = _cfg.capacity;
                cui.loadLabel.text = $"{riders}/{cap}";

                // dots
                int dotCount = Mathf.Min(riders, 18);
                var dotsT    = cui.dotsParent;
                // clear old dots immediately so layout sees only new children
                for (int d = dotsT.childCount - 1; d >= 0; d--)
                    DestroyImmediate(dotsT.GetChild(d).gameObject);
                for (int d = 0; d < dotCount; d++)
                {
                    var dot = CKUI.Box(dotsT, "Dot", Amber);
                    dot.sprite = _circleSprite;
                    var drt = dot.rectTransform;
                    var dle = dot.gameObject.AddComponent<LayoutElement>();
                    dle.minWidth = dle.minHeight = 5;
                    dle.flexibleWidth = 0;
                }

                // direction indicator
                Color dirColor = car.dir > 0 ? Amber : SteelBright;
                cui.dirTriangle.color = dirColor;
            }

            // Observation
            if (showObservation && _obsLocations != null)
            {
                _sb.Clear();
                _sb.Append("car_locations: [");
                for (int i = 0; i < _cfg.numElevators; i++)
                {
                    if (i > 0) _sb.Append("  ");
                    _sb.Append(_b.cars[i].Floor);
                }
                _sb.Append("]");
                _obsLocations.text = _sb.ToString();

                _sb.Clear();
                for (int i = 0; i < _cfg.numElevators; i++)
                {
                    _sb.Append($"E{i} ");
                    for (int f = 0; f < NF; f++)
                        _sb.Append(_b.cars[i].WantsFloor(f) ? '1' : '0');
                    if (i < _cfg.numElevators - 1) _sb.Append('\n');
                }
                _obsButtons.text = _sb.ToString();
                _obsButtons.color = (_cfg.numElevators > 0 && _b.cars[0].riders.Count > 0)
                    ? Amber : TextMuted;

                _sb.Clear();
                _sb.Append("hall [up dn]: ");
                for (int f = 0; f < NF; f++)
                {
                    _sb.Append(_b.upQ[f].Count > 0 ? '1' : '0');
                    _sb.Append(_b.downQ[f].Count > 0 ? '1' : '0');
                    if (f < NF - 1) _sb.Append(' ');
                }
                _obsHall.text = _sb.ToString();
            }
        }

        void RefreshTileRow(Transform track, List<Passenger> queue, bool up)
        {
            // Clear old tiles immediately so layout sees only the new children this frame
            for (int c = track.childCount - 1; c >= 0; c--)
                DestroyImmediate(track.GetChild(c).gameObject);

            int show = Mathf.Min(queue.Count, MaxTiles);
            for (int t = 0; t < show; t++)
            {
                var p       = queue[t];
                bool urgent = p.waitTime >= 0.8f * _cfg.maxWait;

                var tile = CKUI.Panel(track, $"Tile{t}", Raised);
                tile.sizeDelta = new Vector2(18, _tileH);
                AddBorder1px(tile, urgent ? Coral : Border);
                tile.gameObject.AddComponent<LayoutElement>().flexibleWidth = 0;

                string destTxt = p.dest == 0 ? "G" : p.dest.ToString();
                var lbl = CKUI.Label(tile, "Dest", destTxt, monoFont, 9,
                    urgent ? CoralBright : TextSecondary, TextAlignmentOptions.Midline);
                CKUI.Stretch(lbl.rectTransform, 0, 0, 2, 4);

                // wait fill bar at bottom
                float waitFrac = Mathf.Clamp01(p.waitTime / _cfg.maxWait);
                var bar = CKUI.Box(tile, "WaitBar", urgent ? Coral : Amber);
                var barRt = bar.rectTransform;
                barRt.anchorMin = Vector2.zero;
                barRt.anchorMax = new Vector2(0, 0);
                barRt.pivot = new Vector2(0, 0);
                barRt.anchoredPosition = Vector2.zero;
                barRt.sizeDelta = new Vector2(waitFrac * 18f, 2);
            }

            if (queue.Count > MaxTiles)
            {
                int more = queue.Count - MaxTiles;
                var more_lbl = CKUI.Label(track, "More", $"+{more}", monoFont, 9, TextMuted,
                    TextAlignmentOptions.MidlineLeft);
                more_lbl.gameObject.AddComponent<LayoutElement>().flexibleWidth = 0;
            }
        }

        // ── Footer state ──────────────────────────────────────────────────────

        void UpdateFooterState()
        {
            if (_playBtnLabel == null) return;

            if (_playing)
            {
                _playBtnLabel.text = "PAUSE";
                var img = _playBtn.GetComponent<Image>();
                img.color = Raised;
                _playBtnLabel.color = AmberBright;
                AddBorder1px(_playBtn.GetComponent<RectTransform>(), Amber);
            }
            else
            {
                _playBtnLabel.text = "PLAY";
                var img = _playBtn.GetComponent<Image>();
                img.color = Amber;
                _playBtnLabel.color = Void;
                RemoveBorders(_playBtn.GetComponent<RectTransform>());
            }

            _stepBtn.interactable = !_playing;
            var stepImg = _stepBtn.GetComponentInChildren<TextMeshProUGUI>();
            if (stepImg) stepImg.color = _playing
                ? new Color(TextPrimary.r, TextPrimary.g, TextPrimary.b, 0.4f)
                : TextPrimary;

            if (_dayCycleBtnLabel != null)
                _dayCycleBtnLabel.text = $"DAY CYCLE  {(_dayCycle ? "ON" : "OFF")}";
        }

        // ── Utility ──────────────────────────────────────────────────────────

        static void AddBorder1px(RectTransform rt, Color c)
        {
            RemoveBorders(rt);
            CKUI.BorderTop(rt, c);
            CKUI.BorderBottom(rt, c);
            CKUI.BorderLeft(rt, c);
            CKUI.BorderRight(rt, c);
        }

        static void RemoveBorders(RectTransform rt)
        {
            for (int i = rt.childCount - 1; i >= 0; i--)
            {
                var child = rt.GetChild(i);
                string n = child.name;
                if (n == "BorderTop" || n == "BorderBot" || n == "BorderLeft" || n == "BorderRight")
                    Destroy(child.gameObject);
            }
        }

        static string[] FloorOptions()
        {
            var opts = new string[14];
            for (int i = 0; i < 14; i++) opts[i] = (i + 3).ToString();
            return opts;
        }

        static int CapIndex(int cap)
        {
            var caps = new[] { 4, 6, 8, 10, 12, 16 };
            for (int i = 0; i < caps.Length; i++)
                if (caps[i] == cap) return i;
            return 2; // default 8
        }
    }
}
