using UnityEngine;

namespace ElevatorRL
{
    public enum TrafficPattern { UpPeak = 0, DownPeak = 1, Lunch = 2, Midday = 3, Uniform = 4 }

    /// <summary>
    /// Traffic shape: a global intensity multiplier, a default pattern, and an
    /// optional day cycle that auto-selects the pattern by sim time. The actual
    /// per-floor arrival rates and destination matrix are generated by
    /// PassengerArrivals.LoadPatternAtTime() so designers tune intent here, not raw arrays.
    /// </summary>
    [CreateAssetMenu(menuName = "Elevator/Traffic Config", fileName = "TrafficConfig")]
    public sealed class TrafficConfig : ScriptableObject
    {
        [Header("Intensity")]
        [Tooltip("Global arrival-rate multiplier (the 'traffic' slider).")]
        [Range(0f, 4f)] public float intensity = 1.0f;

        [Tooltip("EXPERIMENT_PLAN.md E15. Building population, used by the paper's inter-arrival " +
            "formula: arrivals/sec = ar * population / 30000. The 2024 paper uses 1200 for a 20-floor " +
            "building with 4 cars x capacity 20 (= 80 carrying slots), giving ~1,009-1,612 arrivals/hr " +
            "= ~16 arrivals/hr per slot. Rung M has 5 cars x capacity 8 (= 40 slots), i.e. HALF their " +
            "carrying capacity, so 600 reproduces their load-per-slot. (The old hand-tuned lambdas ran " +
            "~8,640/hr = 216/hr/slot -- 13.3x more loaded, which is why 'sweep continuously' i.e. LOOK " +
            "was near-optimal and RL had nothing to exploit.) Scale this with fleet capacity, not floors.")]
        [Min(1)] public int population = 600;

        [Header("Pattern")]
        public TrafficPattern defaultPattern = TrafficPattern.UpPeak;

        [Header("Day cycle (optional)")]
        public bool useDayCycle = false;
        [Tooltip("Real seconds for one full simulated 24h day.")]
        [Min(1f)] public float dayLengthSeconds = 1200f;
        [Range(0f, 24f)] public float startHour = 6f;

        /// <summary>Maps a sim time to the active pattern when the day cycle is on.</summary>
        public TrafficPattern PatternForTime(float simSeconds)
        {
            float dayFrac = Mathf.Repeat(simSeconds / Mathf.Max(1f, dayLengthSeconds), 1f);
            float hour = Mathf.Repeat(startHour + dayFrac * 24f, 24f);
            if (hour >= 6f && hour < 10f) return TrafficPattern.UpPeak;
            if (hour >= 11f && hour < 14f) return TrafficPattern.Lunch;
            if (hour >= 16f && hour < 19f) return TrafficPattern.DownPeak;
            return TrafficPattern.Midday;
        }

        public float DayFraction(float simSeconds)
        {
            return Mathf.Repeat((startHour / 24f) + simSeconds / Mathf.Max(1f, dayLengthSeconds), 1f);
        }
    }
}
